### ISSUE TITLE
Connect with with https url

### ISSUE THREAD

**Issue by josephkandi** [Quobject/SocketIoClientDotNet#84]
When i connect to my server over an **https** connection my connect fails but works fine over **http**. I can connect fine over https if i use the native Android socket.io client. So the issue is not with the certificate. Am using Xamarin.Android. I think the issue is also on this SO link, http://stackoverflow.com/questions/4926676/mono-webrequest-fails-with-https

**Comment by ChickenMythic** [comment]
I could not connect over HTTPS too. (The server config is fine as I could connect using an external tool).
I am working on a WinRT Universal app 8.1.

I also tried to set IgnoreServerCertificateValidation to true, without any result.

**Comment by ChickenMythic** [comment]
I my case the issue came from the client side options.
Related to this post:
https://github.com/Quobject/SocketIoClientDotNet/issues/87

By setting those Transport values in my client Options, I could connect over HTTPS:
```
options.Transports = Quobject.Collections.Immutable.ImmutableList<string>.Empty;
options.Transports = options.Transports.Add("websocket");
options.Transports = options.Transports.Add("flashsocket");
options.Transports = options.Transports.Add("htmlfile");
options.Transports = options.Transports.Add("xhr-polling");
options.Transports = options.Transports.Add("jsonp-polling");
```
However, even if the server uses a specific port for socket.io communications, I had to not specify the port in my client Uri neither in the client options, otherwise HTTPS connection failed.
(But, for HTTP connection I have to specify the port in both Uri and options).

**Comment by josephkandi** [comment]
I changed the library, am using this library,https://github.com/mattleibow/Socket.IO.Client, which a Xamarin binding to the Socket.IO native java client. SSL works fine without a problem
